version: '3.9'
services:
  backend:
    container_name: wbmc-backend
    build:
          context: ./backend
          dockerfile: Dockerfile
    environment:
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - REDIS_PORT=${REDIS_PORT}
      - BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
      - REDIS_HOST=redis
      - BACKEND_ADDRESS=${BACKEND_ADDRESS}
    networks:
      - wbcm-backend
      - wbcm-frontend
    ports:
      - ${CONTAINER_BACKEND_PORT}:80
    depends_on:
      - redis

  redis:
    container_name: wbmc-redis
    image: redis:alpine
    restart: always
    networks:
      - wbcm-backend
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}


networks:
  wbcm-frontend:
  wbcm-backend:
