"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p121ah##ig1$ir^b%+176k=j@5ikdvha%*bkr87$-&jeue+j=k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'backend.api.apps.ApiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ariadne_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'




# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'


#=---------------- COUNTRY API SETTINGS -----------------=#

FROM_NET_KEY_TO_FIELD_VALUE: dict = {
    # api-key : dict-key
    'NY.GDP.MKTP.CD': 'GDP',
    'SP.POP.TOTL': 'totalPopulation',
    'SE.ADT.1524.LT.ZS': 'literacyRate',
    'SI.POV.GINI': 'giniIndex',
    'EG.ELC.ACCS.ZS': 'eletricityAccess'
}
BASIC_INFO_FIELD: str = 'basicInfo'

#=---------------- REQUEST COUNTRY URL -----------------=#
API_URL_ROOT: str = 'api.worldbank.org'
API_VERSION: str = 'v2'
API_COUNTRY_URL: str = '/'.join((API_VERSION, 'country'))
API_INDICATOR_URL: str = 'indicator'

#=---------------- REDIS SETTINGS -----------------=#
REDIS = {
    'port': 6379,
    'charset' : 'utf-8',
    'decode_responses' : True
}