"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from typing import Dict, Union
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


INSTALLED_APPS = [
    'app.api.apps.ApiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ariadne_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

#=---------------- COUNTRY API SETTINGS -----------------=#
API_INDICATOR_URL: str = 'indicator'
API_BASIC_INFO_URL: str = ''
FROM_NET_KEY_TO_DICT_VALUE: Dict[str, str] = {
    # api-key : dict-key
    API_BASIC_INFO_URL                    : 'basicInfo',
    API_INDICATOR_URL+'/NY.GDP.MKTP.CD'   : 'GDP',
    API_INDICATOR_URL+'/SP.POP.TOTL'      : 'totalPopulation',
    API_INDICATOR_URL+'/SE.ADT.1524.LT.ZS': 'literacyRate',
    API_INDICATOR_URL+'/SI.POV.GINI'      : 'giniIndex',
    API_INDICATOR_URL+'/EG.ELC.ACCS.ZS'   : 'eletricityAccess'
}

API_URL_ROOT: str = 'api.worldbank.org'
API_VERSION: str = 'v2'
API_COUNTRY_URL: str = '/'.join((API_VERSION, 'country'))


#=---------------- REDIS SETTINGS -----------------=#
RedisVal = Union[str, bool, int]
REDIS: Dict[str, RedisVal] = {
    'host': os.getenv('REDIS_HOST'),
    'port': int(os.getenv('REDIS_PORT', '6379')),
    'charset': os.getenv('REDIS_CHARSET','utf-8'),
    'decode_responses': os.getenv('REDIS_DECODE_RESPONSES', 'True').lower() == 'true',
    'expire_key_in_days': int(os.getenv('REDIS_EXPIRE_KEY_IN_DAYS', '10')),
    'username': os.getenv('REDIS_USERNAME'),
    'password': os.getenv('REDIS_PASSWORD'),
    'db': int(os.getenv('REDIS_DB', '1')),
}