name: Quality

on: [pull_request, push]

env:
    backend-directory: ./backend
    frontend-directory: ./frontend

jobs:
  backend-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.backend-directory}}/
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Linter validation
        run: python -m pylint * --ignore=venv,requirements.txt,Dockerfile

  frontend-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.frontend-directory}}/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
        cache-dependency-path: '${{env.frontend-directory}}/package-lock.json'

    - name: Install Packages
      run: npm install

    - name: Linter validation
      run: npm run lint

    - name: Jsdoc generator
      run: npx jsdoc -r -c ./.jsdoc.conf.json
